#!/bin/bash

if git log origin/$(git rev-parse --abbrev-ref HEAD)..HEAD --oneline | grep -i "feat"; then
  # display error message in red
  echo -e "\n\033[31mError: Found 'feat' in local commit. Please fix before pushing.\033[0m"
  exit 1
fi

git push origin "${1:-$(git current-branch)}"
