name: bluesky-yui-card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: myConsciousness/bluesky-post@v2
        with:
          text: "@yui.bsky.social /card"
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
