name: promote_post

on:
  schedule:
    # jp 12,21
    - cron: "0 3,12 * * *"
    # jp 13,19
    - cron: "0 4,10 * * *"

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
      - name: promote sizu
        if: github.event.schedule == '0 3,12 * * *'
        working-directory: ./deno
        env:
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          TEXTDB_ENDPOINT: ${{ secrets.TEXTDB_ENDPOINT }}
        run: deno task promote_rss sizu
      - name: promote zenn
        if: github.event.schedule == '0 4,10 * * *'
        working-directory: ./deno
        env:
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          TEXTDB_ENDPOINT: ${{ secrets.TEXTDB_ENDPOINT }}
        run: deno task promote_rss zenn
