name: draw-yui-card

on:
  workflow_dispatch:
  schedule:
    - cron: "30 15 * * *"

jobs:
  yui_card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
      - name: post to bsky
        working-directory: ./deno
        env:
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: deno task yui
