name: draw-yui-card

on:
  workflow_dispatch:
  schedule:
    - cron: "30 20 * * *"

jobs:
  udd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
      - name: post to bsky
        working-directory: ./deno
        env:
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        run: deno task yui
