name: draw-yui-card

on:
  schedule:
    - cron: "30 19 * * *"
  repository_dispatch:
    types:
      - raid

jobs:
  yui_card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
      - name: post to bsky
        if: ${{ github.event_name == 'schedule' }}
        working-directory: ./deno
        env:
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: deno task yui
      - name: raid battle
        if: ${{ github.event_name == 'repository_dispatch' }}
        working-directory: ./deno
        env:
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: deno task yui raid
